
#A
ASSETS_PATH = 'asset/'

#C
CELL_SIZE = 40
CELL_NUMBER = 20
COLOR_ORANGE = (255, 128, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_YELLOW = (255, 255, 0)
COLOR_GOLD = (255, 215, 0)

# Opções do menu
MENU_OPTION = ('START',
               'SCORE',
               'EXIT')

#S
SCREEN_WIDTH = CELL_NUMBER * CELL_SIZE
SCREEN_HEIGHT = CELL_NUMBER * CELL_SIZE




